version: "3"

services:
  web:
    image: mavasdemo:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 500M
      restart_policy:
        condition: none
        max_attempts: 1
    ports:
      - "18110:80"